export const JWT_PUBLIC_KEY =
  process.env.JWT_PUBLIC_KEY ||
  `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvczOuYE6Pq7wcBZbMU8z
Kg8uHzBQYbZSxcQgCVpYnmM3B7xkYQ/I7n20RmAdTK0Hfvv/CuC+/yEVprnl0AAJ
OBL5fi307duo5oGGj4FE8GYYcY4qKUlFEuSIR8I3jdNgW8bS4OXUzKNUNnwtgaVV
62qyOXuLL2iWd3kwOLS1Yl8FzhBZ+Mrom6CqsZHDUuCLSALCREyEYU4FXdb+DAnW
ftFdLRIrDME5dMbqmoCeCel3iT0pnojAurCq+ja0V3ETM8fg6FN+dMNZQGnXQxZQ
blt70DP7OHqKOY0vEcxks4aXbAxwEAjesuEnWG85QzcL/jCuvaw+Wg+CjK7p7Va5
JwIDAQAB
-----END PUBLIC KEY-----`;
